### ISSUE TITLE
Unable to use `=== "expand(cat .datasets.txt | tr -d '[]')"`

### ISSUE THREAD

**Issue by KastanDay** [project-codeflare/codeflare-cli#769]
Hi Nick, 

I'm trying to write CodeFlare-CLI guidebooks. I've slowly been learning the syntax over the past 6 months. But I'm getting inconsistent performance with the `expand` keyword. It's broken with both relative paths and fully specified absolute paths.

It works in my primary guidebook `index.md` but not when imported via a snippet in `data_movement_select_destination.md`
When broken, it looks like this:
![CleanShot 2023-02-09 at 14 41 32](https://user-images.githubusercontent.com/13607221/217934557-2ccb9d6f-7fdd-4b74-b418-0dc2e186a15c.png)

For example, in `index.md`
```
## Select the Clowder dataset you whish to transfer. 
=== "expand(cat .available_clowder_datasets.txt | tr -d '[]')"
    ```shell
    echo "👉 Selected source dataset: ${choice}"
    ```

    # Select the destination location.
    --8<-- "CodeFlare-Extractors/codeflare_helpers/data_movement_select_destination.md"
```
Then I use the snippit notation to import `CodeFlare-Extractors/codeflare_helpers/data_movement_select_destination.md`

```
## Select the destination location

=== "Destination: Clowder Dataset"
    Select from available datasets in Clowder, or create a new dataset to be the destination. 
    ```shell
    echo "where are we"
    pwd
    which cat
    ```

    ## Select the destination Clowder dataset.
    === "expand(cat .available_clowder_datasets.txt | tr -d '[]')"
        ```shell
        echo "👉 Selected destination dataset: ${choice}"
        ```
```

Any idea how to fix my expand operator?

**Comment by starpit** [comment]
hiya kastan! first, to level set: which version of madwizard are you using?

second, can you try running with `DEBUG=madwizard/groups/expansion`?

**Comment by KastanDay** [comment]
Thanks Nick!

Using `codeflare: 2.4.1` but I'll update now. 

Here's with debugging enabled. Note it's pasted twice here, just in case 

```
✔  Choice 7  Select the destination Clowder dataset.  · expand(cat .available_clowder_datasets.txt | tr -d '[]')
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] {
  GUIDEBOOK_DASHDASH: '',
  CLOWDER_HOSTNAME: 'http://localhost:8000',
  CLOWDER_API_KEY: 'bbe2dce9-c3eb-4188-8a70-1d6e676beeb1'
} +0ms
?  Choice 8  Select the destination Clowder dataset.  …
❯ expand(cat .available_clowder_datasets.txt | tr -d '[]')  ◄ prior choice
```

**Comment by starpit** [comment]
i just tried 5.2.6, and it seems ok. i wonder if some bugs were fixed along the way? i tried both with a foo.md (using your content), and with a bar.md that `--8<--` snippet-inlines foo.md

**Comment by starpit** [comment]
oh sorry, i was referring to madwizard@5.2.6. let me try with the codeflare cli front-end.

**Comment by KastanDay** [comment]
Ah thanks. I updated codeflare to `2.4.1` and I'm still facing the issue. Maybe my problem has to do with `cat`ing a file that's above me in the file system? 

Here's `. available_clowder_datasets.txt`
```text
first dataset
my_2nd_dataset
```

**Comment by starpit** [comment]
thanks. could you paste the first part of the log. i wonder if there is an error up there. (you had pasted the bottom part?)

**Comment by KastanDay** [comment]
Yep, sorry I was trying to figure out how much to share, but here's the whole thing. It gets stuck in a loop after this.

```
✔  Choice 1  Welcome to CodeFlare-Clowder Extractor Examples and Tamplates  · ↔️  Move in and out of Clowder
▶ Welcome to CodeFlare-Clowder Extractor Examples and Tamplates


  👉 Starting Clowder with extractors
setenv: invalid argument
🌐 Starting Clowder (http://localhost:8000) in your default browser
❓ It may take up to a minute for the containers to start up, please try refreshing the page a few times.
✔  Choice 2  Select the data you wish to transfer (data source)  · Source: Clowder Dataset
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] { GUIDEBOOK_DASHDASH: '' } +0ms
✔  Choice 3  Configure your Clowder authentication
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] { GUIDEBOOK_DASHDASH: '' } +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] { GUIDEBOOK_DASHDASH: '', CLOWDER_HOSTNAME: 'http://localhost:8000' } +0ms
✔  Choice 4  Clowder API key
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] { GUIDEBOOK_DASHDASH: '', CLOWDER_HOSTNAME: 'http://localhost:8000' } +0ms
▶ Clowder API key


http://localhost:8000
bbe2dce9-c3eb-4188-8a70-1d6e676beeb1
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] {
  GUIDEBOOK_DASHDASH: '',
  CLOWDER_HOSTNAME: 'http://localhost:8000',
  CLOWDER_API_KEY: 'bbe2dce9-c3eb-4188-8a70-1d6e676beeb1'
} +1ms
✔  Choice 5  Select the Clowder dataset you whish to transfer.  · my_2nd_dataset
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] {
  GUIDEBOOK_DASHDASH: '',
  CLOWDER_HOSTNAME: 'http://localhost:8000',
  CLOWDER_API_KEY: 'bbe2dce9-c3eb-4188-8a70-1d6e676beeb1'
} +0ms
👉 Selected source dataset: my_2nd_dataset
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] {
  GUIDEBOOK_DASHDASH: '',
  CLOWDER_HOSTNAME: 'http://localhost:8000',
  CLOWDER_API_KEY: 'bbe2dce9-c3eb-4188-8a70-1d6e676beeb1'
} +0ms
✔  Choice 6  Select the destination location  · Destination: Clowder Dataset
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] {
  GUIDEBOOK_DASHDASH: '',
  CLOWDER_HOSTNAME: 'http://localhost:8000',
  CLOWDER_API_KEY: 'bbe2dce9-c3eb-4188-8a70-1d6e676beeb1'
} +0ms
where are we
/Users/kastanday/code/ncsa/clean_clowder_no_edits/another/clowder
/bin/cat
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] {
  GUIDEBOOK_DASHDASH: '',
  CLOWDER_HOSTNAME: 'http://localhost:8000',
  CLOWDER_API_KEY: 'bbe2dce9-c3eb-4188-8a70-1d6e676beeb1'
} +0ms
✔  Choice 7  Select the destination Clowder dataset.  · expand(cat .available_clowder_datasets.txt | tr -d '[]')
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } memoized +0ms
  madwizard/groups/expansion {
  madwizard/groups/expansion   expr: "cat .available_clowder_datasets.txt | tr -d '[]'",
  madwizard/groups/expansion   message: undefined,
  madwizard/groups/expansion   key: undefined
  madwizard/groups/expansion } [ 'my_2nd_dataset', 'nice images' ] {
  GUIDEBOOK_DASHDASH: '',
  CLOWDER_HOSTNAME: 'http://localhost:8000',
  CLOWDER_API_KEY: 'bbe2dce9-c3eb-4188-8a70-1d6e676beeb1'
} +0ms
?  Choice 8  Select the destination Clowder dataset.  …
❯ expand(cat .available_clowder_datasets.txt | tr -d '[]')```

**Comment by KastanDay** [comment]
Update. 
This works: 
```
## Select the destination location

=== "Destination: Clowder Dataset"
    Select from available datasets in Clowder, or create a new dataset to be the destination. 

## Select the destination Clowder dataset.
HI HI HI
=== "expand(cat .v2_available_clowder_datasets.txt | tr -d '[]')"
    ```shell
    echo "👉 Selected destination dataset: ${choice}"
    ```
```

This is does not work (same as above):
```
## Select the destination location

=== "Destination: Clowder Dataset"
    Select from available datasets in Clowder, or create a new dataset to be the destination. 

## Select the destination Clowder dataset.
HI HI HI
=== "expand(cat .v2_available_clowder_datasets.txt | tr -d '[]')"
    ```shell
    echo "👉 Selected destination dataset: ${choice}"
    ```
```

Any idea what I'm messing up here? Am I not allowed to nest these?

**Comment by KastanDay** [comment]
To your thoughts:
1. Yes. I'm trying to show the _exact same_ list twice (to choose a source and destination).

Ah yes, it did feel like a side-effect from the memorization functionality. I'll try that.

2. Thank you so much for pointing out the difference between `:import{}` and `--8<--`

With this I'll be able to resolve it. Much appreciated.

**Comment by starpit** [comment]
great. there are some more complex abstraction mechanisms to avoid duplicating your choose-dataset into `clowder/choose/dataset/input` and `/output`... but let's see if just cloning the logic into two separate guidebook files works for you, to start with.
